import Head from "next/head";
import Button from "../components/button";
import styles from "../styles/Home.module.css";

// Dummy users data this will need to be fetched from the api
// Implement this in the apis/get-all-users file more instructions there
const users = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: {
        lat: "-37.3159",
        lng: "81.1496",
      },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: {
        lat: "-43.9509",
        lng: "-34.4618",
      },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
];

/**
 * This is the function that is called as soon as this page is routed to which is localhost:3000
 * @returns JSX.Element
 */
export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vidzing React Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        {/** Example of reusable component */}
        <Button>Click me</Button>

        {/**
         * This will need to be a reusable component that can be passed users data and render
         * all users that are returned
         */}
        <div className={styles.card}>
          <h2>{users[0].name}</h2>
          <div className={styles.cardInfo}>
            <span>{users[0].company.name}</span>
            <span>{users[0].company.catchPhrase}</span>
            <span>{users[0].company.bs}</span>
          </div>
          <div className={styles.cardFooter}>
            <span>{users[0].email}</span>
            <span>{users[0].phone}</span>
            <span>{users[0].website}</span>
          </div>
        </div>

        <div className={styles.card}>
          <h2>{users[1].name}</h2>
          <div className={styles.cardInfo}>
            <span>{users[1].company.name}</span>
            <span>{users[1].company.catchPhrase}</span>
            <span>{users[1].company.bs}</span>
          </div>
          <div className={styles.cardFooter}>
            <span>{users[1].email}</span>
            <span>{users[1].phone}</span>
            <span>{users[1].website}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
