import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import ApiCall from '../apis/get-all-users/ApiCall'
import CardGrid from '../components/grid/Grid'

const Home = () => {
  const [userData, setUserData] = useState()

  const fetchedDataHandler = fetchedData => { 
    console.log(fetchedData);
    console.log('Data fetched from API.');
    setUserData(fetchedData);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Vidzing React Test</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ApiCall sendDataToParent={fetchedDataHandler}>
        API call
      </ApiCall>
      <div className={styles.main}>
        {userData === null && <p>Loading...</p>}
        {userData != null && <CardGrid cardData={userData} />}
      </div>
    </div>
  )
}

export default Home;
